modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "physo"
version = "${version}"
displayName = "Physics Overhaul"
authors = "Sasai_Kudasai_BM"
description = '''

'''
logoFile = "assets/physo/icon.png"

[[dependencies.example_mod]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.example_mod]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.example_mod]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "physics_overhaul.mixins.json"
